definitions:
  config:
    /hst:hst/hst:hosts/dev-localhost:
      .meta:residual-child-node-category: content
      jcr:primaryType: hst:virtualhostgroup
      hst:defaultport: 8080
      /localhost:
        .meta:residual-child-node-category: content
        jcr:primaryType: hst:virtualhost
        /hst:root:
          .meta:residual-child-node-category: content
          jcr:primaryType: hst:mount
          hst:homepage: root
          hst:mountpoint: /hst:myproject/hst:sites/b2c
          hst:alias: b2c
          /b2b:
            .meta:residual-child-node-category: content
            jcr:primaryType: hst:mount
            hst:mountpoint: /hst:myproject/hst:sites/b2b
            hst:homepage: root
            hst:alias: b2b
